name: Backend CI - Test, Build and Push Images to ACR

# Trigger on push to 'testing' branch or manual dispatch
on:
  push:
    branches:
      - testing
  workflow_dispatch:
    paths:
      - 'customer-service/**'
      - 'order-service/**'
      - 'product-service/**'
      - 'frontend/**'
      - '.github/workflows/backend_ci.yml'

env:
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  # Job 1: Run tests for all services
  test_backends:
    runs-on: ubuntu-latest

    steps:
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: List repository
        run: ls -R
      
      
      # Install dependencies
      - name: Install dependencies - Customer Service
        working-directory: backend/customer-service
        run: npm install

      - name: Install dependencies - Order Service
        working-directory: backend/order-service
        run: npm install

      - name: Install dependencies - Product Service
        working-directory: backend/product-service
        run: npm install

      - name: Install dependencies - Frontend
        working-directory: frontend
        run: npm install

      # Run tests
      - name: Run Customer Service Tests
        working-directory: backend/customer-service
        run: npm test

      - name: Run Order Service Tests
        working-directory: backend/order-service
        run: npm test

      - name: Run Product Service Tests
        working-directory: backend/product-service
        run: npm test

      - name: Run Frontend Tests
        working-directory: frontend
        run: npm test

  # Job 2: Build and Push Docker images (runs only if tests pass)
  build_and_push_images:
    runs-on: ubuntu-latest
    needs: test_backends

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ env.ACR_LOGIN_SERVER }}

      - name: Build and Push Customer Service Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/customer-service:latest ./customer-service
          docker push ${{ env.ACR_LOGIN_SERVER }}/customer-service:latest

      - name: Build and Push Order Service Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/order-service:latest ./order-service
          docker push ${{ env.ACR_LOGIN_SERVER }}/order-service:latest

      - name: Build and Push Product Service Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/product-service:latest ./product-service
          docker push ${{ env.ACR_LOGIN_SERVER }}/product-service:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ./frontend
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:latest

      - name: Logout from Azure
        run: az logout
        if: always()
