name: Backend CI - Test, Build and Push Images to ACR

on:
  push:
    branches:
      - testing
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  test_backends:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Customer Service
      - name: Install dependencies - Customer Service
        working-directory: backend/customer_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Customer Service Tests
        working-directory: backend/customer_service
        run: pytest tests/test_main.py --maxfail=1 --disable-warnings -q

      # Order Service
      - name: Install dependencies - Order Service
        working-directory: backend/order_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Order Service Tests
        working-directory: backend/order_service
        run: pytest tests/test_main.py --maxfail=1 --disable-warnings -q

      # Product Service
      - name: Install dependencies - Product Service
        working-directory: backend/product_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Product Service Tests
        working-directory: backend/product_service
        run: pytest tests/test_main.py --maxfail=1 --disable-warnings -q

      # ---------------------------
      # Stage 1: Test frontend (Node.js)
      # ---------------------------
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Run Frontend Tests
        working-directory: frontend
        run: npm test

  # ---------------------------
  # Stage 2: Build and Push Docker Images
  # ---------------------------
  build_and_push_images:
    runs-on: ubuntu-latest
    needs: test_backends

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ env.ACR_LOGIN_SERVER }}

      # Build & push Docker images
      - name: Build & Push Customer Service
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/customer_service:latest ./backend/customer_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/customer_service:latest

      - name: Build & Push Order Service
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/order_service:latest ./backend/order_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/order_service:latest

      - name: Build & Push Product Service
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/product_service:latest ./backend/product_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/product_service:latest

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ./frontend
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:latest

      - name: Logout from Azure
        run: az logout
        if: always()
