name: Backend CI - Test, Build and Push Images to ACR

on:
  push:
    branches:
      - testing
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  # ---------------------------
  # Job 1: Tests and linting (COMMENTED OUT)
  # -------------------g--------
  # test_and_lint_backends:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     # other steps...

  # ---------------------------
  # Job 2: Build and Push Images (COMMENTED OUT)
  # ---------------------------
  # build_and_push_images:
  #   runs-on: ubuntu-latest
  #   needs: test_and_lint_backends
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     # other steps...

  # ---------------------------
  # Job 3: Deploy to Staging (ACTIVE)
  # ---------------------------
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Needs to be set as a GitHub Secret (Service Principal JSON)

    # Login to Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        run: az acr login --name ${{ env.ACR_LOGIN_SERVER }}




      - name: Deploy Product Service
        run: |
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} \
              -p ${{ secrets.AZURE_CLIENT_SECRET }} \
              --tenant ${{ secrets.AZURE_TENANT_ID }}

            az container create \
            --resource-group sk10-rg \
            --name product-service-staging \
            --image ${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.IMAGE_TAG }} \
            --cpu 1 --memory 1 \
            --restart-policy Never