name: Backend CI - Test, Build and Push Images to ACR

on:
  push:
    branches:
      - testing
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  # ---------------------------
  # Job 1: Tests and linting (COMMENTED OUT)
  # ---------------------------
  # test_and_lint_backends:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     # other steps...

  # ---------------------------
  # Job 2: Build and Push Images (COMMENTED OUT)
  # ---------------------------
  # build_and_push_images:
  #   runs-on: ubuntu-latest
  #   needs: test_and_lint_backends
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     # other steps...

  # ---------------------------
  # Job 3: Deploy to Staging (ACTIVE)
  # ---------------------------
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Product Service
        run: |
          RG_NAME=sk10-rg
          az container create \
            --resource-group $RG_NAME \
            --name product-service-staging \
            --image ${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.IMAGE_TAG }} \
            --cpu 1 --memory 1 \
            --restart-policy Never \
            --registry-login-server ${{ env.ACR_LOGIN_SERVER }}

      - name: Deploy Order Service
        run: |
          RG_NAME=sk10-rg
          az container create \
            --resource-group $RG_NAME \
            --name order-service-staging \
            --image ${{ env.ACR_LOGIN_SERVER }}/order_service:${{ env.IMAGE_TAG }} \
            --cpu 1 --memory 1 \
            --restart-policy Never \
            --registry-login-server ${{ env.ACR_LOGIN_SERVER }}

      - name: Deploy Customer Service
        run: |
          RG_NAME=sk10-rg
          az container create \
            --resource-group $RG_NAME \
            --name customer-service-staging \
            --image ${{ env.ACR_LOGIN_SERVER }}/customer_service:${{ env.IMAGE_TAG }} \
            --cpu 1 --memory 1 \
            --restart-policy Never \
            --registry-login-server ${{ env.ACR_LOGIN_SERVER }}

      - name: Run Simple Acceptance Tests
        run: |
          echo "Run trivial acceptance tests here, e.g., curl /health endpoints"

      - name: Logout from Azure
        run: az logout
